### ISSUE TITLE
Deleted/archived projects are still present in the API response

### ISSUE THREAD

**Issue by thecatontheflat** [toggl/toggl_api_docs#203] opened 2016-09-18 10:25 UTC
Hi!

I've noticed that when requesting `/me` endpoint, its response still contains deleted and archived projects.

So far I am able to distinguish them only by those (not obvious) properties:
- `active: false` for archived project
- `server_deleted_at: ...` for deleted project

Is it expected behaviour?

Cheers,
Vit

**Comment by tutvuvu** [comment] 2017-12-24 20:48
@thecatontheflat Did you ever find a way to call only active and undeleted projects?

**Comment by thecatontheflat** [comment] 2017-12-25 11:56
@tutvuvu Not really — I filter the results on my end

**Comment by grey280** [comment] 2018-06-22 00:48
I'll second the question about this being intended behavior - having both 'deleted' and 'archived' projects show up in the list returned seems an odd choice. Are 'deleted' projects in a recycle bin sort of thing, and get properly purged after a certain amount of time, or is the difference between 'deleted' and 'archived' just "one can be searched for in the web interface"?

**Comment by joeriharleman** [comment] 2022-06-27 08:13
Hello @thecatontheflat!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl

**Closed by joeriharleman** 2022-06-27 08:13 UTC
