### ISSUE TITLE
Webhook Support

### ISSUE THREAD

**Issue by gpattersonm** [toggl/toggl_api_docs#346] opened 2019-09-27 00:17 UTC
Is it possible to get support for webhooks? I think it would be really great to have this capability so that when integrating work services like Zapier out Integromat that things could be triggered real-time instead of needing to run on a schedule.

**Comment by F-V** [comment] 2020-01-30 11:46
#64 Same issue/request

**Comment by F-V** [comment] 2020-01-30 11:46
Duplicate of #64

**Comment by chrisaligent** [comment] 2020-03-05 06:44
Been asking for this since 2013. Don't hold your breath.
However a Toggl Zapier integration already exists, if that helps:
https://zapier.com/apps/toggl/integrations/webhook

**Comment by kovin** [comment] 2022-06-23 04:46
Webhooks have been implemented :rocket: Announcement in related [issue](https://github.com/toggl/toggl_api_docs/issues/64#issuecomment-1149792924)

**Closed by kovin** 2022-06-23 04:46 UTC
