### ISSUE TITLE
Bulk update time entries tags does not remove

### ISSUE THREAD

**Issue by kanet77** [toggl/toggl_api_docs#200] opened 2016-09-13 04:39 UTC
Did the behavior of [bulk update time entries tags](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#bulk-update-time-entries-tags) change?

Adding tags still works. Removing tags does not.

```
$ curl -v -u <API_TOKEN>:api_token \
>     -H "Content-Type: application/json" \
>     -d '{"time_entry":{"tags":["money"], "tag_action": "remove"}}' \
>     -X PUT https://www.toggl.com/api/v8/time_entries/<TIME_ENTRY_ID>

{
  "data": {
    "id": <TIME_ENTRY_ID>,
    "wid": <WORKSPACE_ID>,
    "billable": false,
    "start": "2016-09-13T04:30:56+00:00",
    "stop": "2016-09-13T04:31:04Z",
    "duration": 8,
    "description": "time entry description",
    "tags": [
      "money"  <---------------- not removed
    ],
    "duronly": false,
    "at": "2016-09-13T04:33:28+00:00",
    "uid": <USER_ID>
  }
}
```

**Comment by loadkpi** [comment] 2017-02-14 23:36
Confirm the issue. It seems that you can't remove all tags which some tag entry has.

For example, if some time entry has ["billed","productive"] tags you can remove "billed" OR "productive" tag using 'remove' tag_action, but you can't remove them together. If you remove "billed" you can't remove "productive" after that.

Reproduced both for updating one time entry and bulk updating.

**Comment by gaumeister** [comment] 2019-03-25 16:34
Checking in on this issue. I see a commit was made Dec 27, 2018. Can we expect it in a release soon?

**Comment by gaumeister** [comment] 2019-07-30 15:26
What's the status on this please? I can still confirm the API does NOT remove tags. The behavior I see is that when only one tag remains on an entry, performing a bulk-remove action will not remove the tag.

When will the fix be released?

**Comment by jdebarizon** [comment] 2021-03-16 18:08
The same behavior still in place in 2021.
It's intermittent deleting the tags. I couldn't find a pattern. Sometimes remove, sometimes don't.

A fix for it would be good. Building integration with an ERP and I'm controlling the workflow statuses via tags. Well, at least trying.

**Comment by roelandkuiper** [comment] 2021-06-14 13:45
They fixed the bug now. At first you couldn't remove the last tag in a bulk action due to a bug, but now it works properly again.

**Comment by joeriharleman** [comment] 2022-06-27 08:14
Hello @kanet77!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl

**Closed by joeriharleman** 2022-06-27 08:14 UTC
